### ISSUE TITLE
Binary Tree

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#119]
Implementation of the following in Python:

- [x] ~~AVL Tree~~

- [x] ~~Basic Binary Tree~~

- [x] ~~Binary Search Tree~~

- [x] ~~Binary Tree traversal~~

- [x] ~~Recursive Binary Search Tree~~

- [x] ~~Lazy Segment Tree~~

- [x] ~~Fenwick Tree~~

- [x] ~~Non-Recursive Segment Tree~~

- [x] ~~Red-Black Tree~~

NEEDS TO BE PUSHED INTO  "**Python/Binary Tree**"

**Comment by akash22022** [comment]
assign me basic binary tree

**Comment by geekquad** [comment]
Assigning Basic Binary Tree and Binary Search Tree to @akash22022

**Comment by ishanvj2207** [comment]
Hey @geekquad I would like to work on Binary Tree Traversal.
And I would need to add 3 traversals ( inorder , preorder, postorder ) for the same na ?

**Comment by pranavkarnani** [comment]
Hey @geekquad i can work on Recursive Binary Search Tree

**Comment by sachincpu** [comment]
Hey, @geekquad  I want to work on the Avl Trees in Python. Please assign this to me.

**Comment by geekquad** [comment]
Hey @ishanvj2207, yes you will need to add all the three traversals. I have edited the issues. 

* Assigning Binary Tree Traversal and Fenwick tree implementation to @ishanvj2207 
* Assigning Recursive Binary Search Tree to @pranavkarnani 
* Assigning AVL tree to @sachincpu .

**Comment by srishtipoudel** [comment]
@geekquad can you assign me recursive binary search?

**Comment by srishtipoudel** [comment]
@geekquad  i want to work on red-black tree

**Comment by sarthakregmi** [comment]
Hello @geekquad, i want to work on lazy segment tree

**Comment by geekquad** [comment]
Assigning Red-Black tree to @srishtipoudel 
Assigning Lazy Segment tree to @sarthakregmi

**Comment by nickymarino** [comment]
Hi @geekquad! I'd like to work on the Non Recursive Segment Tree algorithm if possible

**Comment by geekquad** [comment]
Assigning Non-Recursive Segment Tree to @nickymarino.

**Comment by Sowmyasree101** [comment]
@geekquad Can u assign me with any thing left?

**Comment by jien1103** [comment]
Hello @geekquad can you assign me Binary Search Tree?

**Comment by JaniniRami07** [comment]
Hey @geekquad , can you assign me Lazy Segment Tree?

**Comment by ajyan** [comment]
@geekquad can you assign me to AVL tree?

**Comment by geekquad** [comment]
Hey @jien1103, @JaniniRami07 and @ajyan, I am sorry but these issues have already been assigned to someone else. 
But we have more [here](https://github.com/geekquad/AlgoBook/issues). Please see that if you guys can contribute to soemthing else. Thankyou :)
