### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#120]
Implementation of the following in Python:

- [x] ~~Singly Linked List~~

- [x] ~~Doubly Linked List~~

- [x] ~~Circular Linked List~~

- [x] ~~Implementing Deque using DoublyLinkedList~~

- [x] ~~Printing the elements of a linked list in reverse~~

NEEDS TO BE PUSHED INTO **"Python/Linked List"**

**Comment by saileshbro** [comment]
@geekquad let me do singly and doubly linked list

**Comment by geekquad** [comment]
Hey @saileshbro, I can assign you Doubly Linked list for now. Let me know if you want any other. Thankyou :)

**Comment by vijay5158** [comment]
@geekquad Can you assign me singly linkedlist  ?

**Comment by geekquad** [comment]
> @geekquad Can you assign me singly linkedlist ?

Sure @vijay. For the future, please see that you first ask for an assignment. It is always on a first come first serve basis. 
Assigning singly linked list to @vijay5158

**Comment by geekquad** [comment]
Assigning Doubly Linked List and Circular Linked list to @saileshbro.

**Comment by akash22022** [comment]
assign me printing the  elements of a linked list in reverse

**Comment by geekquad** [comment]
Assigning Printing the elements of a linked list in reverse to @akash22022

**Comment by pranavkarnani** [comment]
Hey @geekquad can i work on Implementing Deque using DoublyLinkedList

**Comment by geekquad** [comment]
Assigning Deque using DoublyLinkedList to @pranavkarnani

**Comment by saileshbro** [comment]
@geekquad  CircularLinkedList is marked. Is it completed?

**Comment by Sowmyasree101** [comment]
@geekquad  can u assign me with any one left?

**Comment by geekquad** [comment]
@saileshbro, no not yet completed but it is assigned to someone.
@Sowmyasree101, heyy! We have more issues now. Please look [here](https://github.com/geekquad/AlgoBook/issues/197).

**Comment by Raghavarora27** [comment]
can u assign me something??what all are left @geekquad

**Comment by geekquad** [comment]
Hey @Raghavarora27, please look [here](https://github.com/geekquad/AlgoBook/issues/197).
