### ISSUE TITLE
Greedy Algorithms

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#124]
Implementation of the following in Python:

- [x] ~~Egyptian Fraction~~

- [x] ~~Huffman Coding~~

- [x] ~~Huffman Decoding~~

- [x] ~~Job Sequencing Problem~~

NEEDS TO BE PUSHED INTO **"Python/Greedy Algorithms"**

**Comment by pranavkarnani** [comment]
Would love to work on this

**Comment by geekquad** [comment]
> Would love to work on this

Which one would you like to work on? @pranavkarnani

**Comment by pranavkarnani** [comment]
I have pushed my changes for Egyptian fractions to a new branch

**Comment by geekquad** [comment]
For the future, please see that you first ask for an assignment. Assigned @pranavkarnani with Egyptian fractions.

**Comment by ishanvj2207** [comment]
Hey @geekquad Would like to work on job sequencing problem !

**Comment by pranavkarnani** [comment]
Hey @geekquad i can work on Huffman Decoding

**Comment by sachincpu** [comment]
Hey, @geekquad  and @MAJOR-BEAST  I want to work on the Huffman decoding. Please assign this to me.

**Comment by geekquad** [comment]
Assigning Huffman Decoding to @sachincpu

**Comment by geekquad** [comment]
Assigning job sequencing problem to @ishanvj2207

**Comment by nkrumahthis** [comment]
Anything for me to work on?

**Comment by geekquad** [comment]
Hey @nkrumahthis, welcome.
We have 1 left [here](https://github.com/geekquad/AlgoBook/issues/119).
However, we are adding more issues, so just stick with us. Please join our Slack channel for any updates. Thank you :)

**Comment by srirupa19** [comment]
Can you assign me Job Sequencing Problem? @geekquad

**Comment by geekquad** [comment]
Assigning Job Sequencing Problem to @srirupa19.

**Comment by dhruvMohapatra** [comment]
Hey, is the job sequencing done or could you assign it to me pls?

**Comment by geekquad** [comment]
Go ahead @dhruvMohapatra.

**Comment by dhruvMohapatra** [comment]
Hey, made a PR for this issue. Please feel free to provide some feedback, thanks.
