### ISSUE TITLE
In repo labels, Hactoberfest is spelled wrong. 

### ISSUE THREAD

**Issue by utkarshbajaj** [geekquad/AlgoBook#130]
The label should Hacktoberfest and not Hactoberfest. 
According to latest guidelines, the PRs won't count if the label is not Hacktoberfest. Please change it.

**Comment by geekquad** [comment]
Hey @utkarshbajaj, can you please share the link for it too? 
But according to the rules which I have gone through, I never came across any such point saying "PRs won't count if the label is not Hacktoberfest." Please look out [here](https://hacktoberfest.digitalocean.com/faq).
Also, I have edited the tags. Thank you.

**Comment by utkarshbajaj** [comment]
Sure, [These are the new updates](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by utkarshbajaj** [comment]
![image](https://user-images.githubusercontent.com/44445191/94986656-1027e400-057e-11eb-99fe-1954c564d213.jpeg)

**Comment by geekquad** [comment]
Thank you so much for the updates @utkarshbajaj. I have made the amendments in the details and topics section and the issue tag too. Please go through them and let me know if I missed something.
