### ISSUE TITLE
Graph Algorithms

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#16]
Implementation of Graph Algorithms: 
Needs to be merged in Python/Graphs.

- [x] ~~A* (A star)~~ 

- [x] ~~Dijkstra’s shortest path algorithm~~

- [x] ~~Dijkstra’s Algorithm for Adjacency List Representation~~

- [x] ~~Kruskal’s Minimum Spanning Tree Algorithm~~

- [x] ~~Bellman-Ford Algorithm~~

- [x] ~~Floyd Warshall Algorithm~~

- [x] Kahns Algorithm

- [x] ~~Peterson Graph Problem~~

- [ ] Steiner Tree

- [ ] Boruvka’s algorithm for Minimum Spanning Tree

- [ ] Karp’s minimum mean  weight cycle algorithm

**Comment by diyajaiswal11** [comment]
Hey @geekquad , I would like to work on Dijkstra’s shortest path algorithm and Floyd Warshall Algorithm. Please assign this to me.

**Comment by MAJOR-BEAST** [comment]
Assigning Dijkstra’s shortest path algorithm and Floyd Warshall Algorithm to @diyajaiswal11

**Comment by SaiAshish2906** [comment]
Hey @geekquad , I would like to work on the Peterson Graph Problem. Please assign this to me,

**Comment by geekquad** [comment]
Assigning Peterson Graph Problem to @SaiAshish2906.

**Comment by rajatsahay** [comment]
Hey @geekquad 
I'd like to work on the A* (A-star) algorithm. Please assign it to me
Thanks

**Comment by geekquad** [comment]
Assigning A* algorithm to @rajatsahay .

**Comment by nileshteji** [comment]
Can i work on java language as well?

**Comment by MAJOR-BEAST** [comment]
> Can i work on java language as well?

Hey @nileshteji, For now we haven't started with any language other than Python. If you want to contribute now, please stick to this language. Also for more updates, you can keep a check.

**Comment by rudrakshi99** [comment]
Hey @geekquad, I would like to work on Kruskal’s Minimum Spanning Tree Algorithm.

**Comment by MAJOR-BEAST** [comment]
Assigning Kruskal’s Minimum Spanning Tree Algorithm to @rudrakshi99

**Comment by vishwasmattur** [comment]
Hey @geekquad  
I would like to work on Dial's algorithm

**Comment by sachincpu** [comment]
Hey @geekquad  and @MAJOR-BEAST  I want to work on

**Comment by MAJOR-BEAST** [comment]
> Hey @geekquad and @MAJOR-BEAST I want to work on the Peterson graph problem. Please assign this to me.

@sachincpu , please check, Peterson graph problem has been already assigned. You look out for other problems.

**Comment by panda311** [comment]
Hey @geekquad , I would like to contribute for Prim's algorithm for  Mininum Spanning Tree ( it is not listed ) with Adjacency Matrix representation.

**Comment by hritik5102** [comment]
Hello @MAJOR-BEAST @geekquad, I would like to work on this issue :)

I would like to add this algorithm in your repo

- [x] **_Kahns sort_**
- [x] **_Prism minimum spanning tree_**

Thank you :)

**Comment by panda311** [comment]
Hey @geekquad @MAJOR-BEAST , I would like to work on Kahn's Algo for topo Sort with Adjacency List Representation.

Thank You :)

PS:  I have already made a pull request for the same ;)

**Comment by hritik5102** [comment]
> Hey @geekquad @MAJOR-BEAST , I would like to work on Kahn's Algo for topo Sort with Adjacency List Representation.
> 
> Thank You :)
> 
> PS: I have already made a pull request for the same ;)

Sorry, @panda311 but this not how things work, first the mentor, should assign a specific task to someone then only he/she can make a pull request. sorry if I hurt you but that is a general rule that we all have to follow.

Thank you :)

**Comment by gabrielknot** [comment]
Hey @geekquad , I would like to work on Kruskal’s Minimum Spanning Tree Algorithm. Please assign this to me.

**Comment by devangmukherjee** [comment]
I'd like to work on Kahn's Algorithm using C++  @geekquad @MAJOR-BEAST

**Comment by sachincpu** [comment]
Hey @MAJOR-BEAST  and @geekquad  sir I want to work on Dijkstra’s Algorithm for Adjacency List Representation. Please assign this to me

**Comment by geekquad** [comment]
Hello @gabrielknot, Kruskal’s Minimum Spanning Tree Algorithm has already been assigned to someone. Please see other issues and see if you can find something else to contribute to. We are adding more issues soon. Thankyou :)

Hey @devangmukherjee, we have not added a C++ track yet. We will let you know soon. For further updates, please join our Slack channel. Thankyou :)

Hey @panda311, please let us assign you first. Since we are following first come first serve, Khans Algorithm is already assigned. Please see other issues and see if you can find something else to contribute to. We are adding more issues soon. Thankyou : 

Assiging:  
* Dijkstra’s Algorithm for Adjacency List Representation to @sachincpu 
* Kahns sort to @hritik5102 

Please comment again if I have missed someone out. Do look out for other issues and see if you can find something else to contribute to. We are adding more issues soon. Thankyou all.

**Comment by geekquad** [comment]
We still have Dial's Algorithm left. It is up for grab!

**Comment by panda311** [comment]
Hey @geekquad I Know Dial's Algo too, Can I contribute with that ?

**Comment by Karanr1** [comment]
Please assign Kahn's Algorithm to me @geekquad

**Comment by geekquad** [comment]
> Please assign Kahn's Algorithm to me @geekquad

Hey @Karanr1, Kahns Algorithm has already been assigned to someone. However, we still have Dial's Algorithm left. Let me know if you want to work on this.

**Comment by gpriya32** [comment]
Hey, i can work on AO* algo. You didn't mention it. .But I can implement it

**Comment by geekquad** [comment]
Sure @gpriya32, go ahead!

**Comment by gpriya32** [comment]
@geekquad check #240 ao*_algorithm commit.

**Comment by Mansi145** [comment]
Hey @geekquad, can you assign Steiner Tree, Boruvka’s algorithm and Karp’s minimum mean weight cycle algorithm to me? I'd like to work on these.

**Comment by geekquad** [comment]
Assigning Steiner Tree, Boruvka’s algorithm, and Karp’s minimum mean weight cycle algorithm to @Mansi145.
