### ISSUE TITLE
Magic square algorithm

### ISSUE THREAD

**Issue by ArunKumar-25** [geekquad/AlgoBook#183]
@geekquad I would like to contribute on this, assign this to me

**Comment by geekquad** [comment]
Hey @ArunKumar-25, please brief me more on this. Thankyou :)

**Comment by ArunKumar-25** [comment]
@geekquad "magic square is a square matrix, whose order is odd and where the sum of the elements for each row or each column or each diagonal is same"
in this issue I will implement a magic square. after this may be work on some application on magic square as checking a matrix is magic square or not.

**Comment by geekquad** [comment]
Awesome. Please continue. Make sure you merge it in **"python/matrix"**. Thankyou :)
