### ISSUE TITLE
Algorithms in C++

### ISSUE THREAD

**Issue by RonLek** [geekquad/AlgoBook#190]
I'd be happy to contribute algorithms in C++. @geekquad let me know what you think of starting contributions in C++.

**Comment by Siddhant-K-code** [comment]
I wanted to add Sorting & Searching Algorithms in C++

**Comment by geekquad** [comment]
@RonLek @Siddhant-K-code awesome guys. Love the spirit.
We are just editing. We will be adding C++ track in a day. Please join us on Slack for any updates. Thankyou :)

**Comment by Siddhant-K-code** [comment]
Please check this issue #198 
I have listed the Sorting Algorithms in C++

**Comment by jigneshoo7** [comment]
assignment me

**Comment by gpriya32** [comment]
I wanted to add some graph traversal, sorting & Searching Algorithms in C++(optimizedone)
