### ISSUE TITLE
Implementation of Beginner Supervised ML Algorithms

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#2]
Implementation of beginner ML Algorithms:

- [x] ~~Naive Bayes~~

- [ ] SVM

- [x] ~~KNN~~

- [x] ~~Linear Regression~~ 

- [x] ~~Logistic Regression~~

- [ ] Decision Tree

- [ ] AdaBoost

- [x] ~~Random Forest~~

- [x] ~~XGBoost~~

- [ ] Boosting

- [ ] Ridge Regression

**Comment by Pranjalmishra30** [comment]
I would like to work on Linear and logistic regression.
Can you please assign the issue to me.

**Comment by geekquad** [comment]
> I would like to work on Linear and logistic regression.
> Can you please assign the issue to me.
 Sure. Remember PRs will be counted from 1st October. Please star the repo too and join the slack channel as well.

**Comment by kritikaparmar-programmer** [comment]
Hey @geekquad I would like to work on KNN.

**Comment by geekquad** [comment]
Assigning KNN to @kritikaparmar-programmer

**Comment by vardhanaleti** [comment]
Hey @geekquad I'd like to work on random forests.

**Comment by chaturvediabhay24** [comment]
HI @geekquad can the implementation could be done using libraries or it needs to be done from scratch?

**Comment by MAJOR-BEAST** [comment]
Assigning **Random Forest** to @vardhanaleti 
Remember PRs will be counted from 1st of Oct.

**Comment by MAJOR-BEAST** [comment]
> HI @geekquad can the implementation could be done using libraries or it needs to be done from scratch?

Hi

**Comment by arpita1899** [comment]
hey @geekquad i want to work on svm , decision tree , and AdaBoost

**Comment by geekquad** [comment]
Assigning SVM, Decision Tree and AdaBoost to @arpita1899

**Comment by vedantpople4** [comment]
I will work on Naive Bayes

**Comment by geekquad** [comment]
> @geekquad I will work on Naive Bayes

Hey @vedantpople4 Naive Bayes is already implemented. However, if you think you can improve that, please go ahead. Thank you.

**Comment by hritik5102** [comment]
Hello @geekquad,  i would like to work on this issue :)

I would like to add this algorithm to your repo ... 

- [x] Decision tree
- [x] Boosting 
- [x] Random forest regression
- [x] Random forest classification
- [x] Ridge regression

Thank you :)

**Comment by MAJOR-BEAST** [comment]
Assigning @hritik5102 with Boosting and Ridge Regression.

**Comment by hritik5102** [comment]
@MAJOR-BEAST Please check the PR #88 

Thank you :)
