### ISSUE TITLE
Searching Algorithms in CPP

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#237]
- [x] ~~Linear Search~~

- [x] ~~Binary Search~~

- [x] Bilinear Search (Improvised version of Linear Search)

- [x] ~~Breadth-First Search~~

- [x] ~~Depth First Search~~

- [x] ~~Exponential Search~~

- [x] ~~Interpolation Search~~

- [x] Z Algorithm

- [x] ~~Fibonacci Search~~

- [x] ~~Jump Search~~

- [x] ~~Ternary Search~~

- [x] ~~Sublist Search~~

- [x] ~~Hash Search~~

**Comment by ArunKumar-25** [comment]
@geekquad assign me Linear search and Binary search. Thanks:)

**Comment by geekquad** [comment]
Assigning Linear search and Binary search to @ArunKumar-25

**Comment by rudrakshi99** [comment]
Hey @geekquad, Please assign me Breadth-First Search and Depth First Search.

**Comment by geekquad** [comment]
Assigning Breadth-First Search and Depth First Search to @rudrakshi99. .

**Comment by srishtipoudel** [comment]
Hey @geekquad  , I want to work on Fibonacci Search

**Comment by Iampradeepkundra** [comment]
can you assign me hash search and sublist search!

**Comment by sarthakregmi** [comment]
Hello @geekquad , I want to work on Z algorithm.

**Comment by geekquad** [comment]
Assigning Fibonacci Search to @srishtipoudel.
Assigning hash search and sublist search to @Iampradeepkundra.
Assigning Z algorithm to @sarthakregmi.

**Comment by iamKushagra** [comment]
Assign me interpolation, ternary and exponential search.

**Comment by geekquad** [comment]
Assigning interpolation, ternary, and exponential search to @iamKushagra.

**Comment by Mansi145** [comment]
Hey @geekquad, I'd like to work on the interpolation search algorithm. Is the issue open for work?

**Comment by AmanSingh0-0** [comment]
Assign me to work on Bilinear Search

**Comment by geekquad** [comment]
Assigning @AmanSingh0-0 with the same.

**Comment by Aarushi11H** [comment]
Assign me to work on Z algorithm

**Comment by geekquad** [comment]
Assigning Z algorithm to @Aarushi11H.
