### ISSUE TITLE
Sorting Algorithms in Cpp

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#238]
- [x] Insertion Sort

- [x] Selection Sort

- [x] Bubble Sort

- [x] Heap Sort

- [x] Quick Sort

- [x] Radix Sort

- [x] Merge Sort

- [x] Wiggle sort

- [x] Tree sort

- [x] Shell sort

- [x] Tim sort

- [ ] Stooge sort

- [x] Recursive Quick Sort

- [x] Recursive Insertion Sort

- [x] Recursive Bubble Sort

- [x] Random Pivot Quick Sort

- [x] Bead Sort

- [ ] Bitonic Sort

- [x] Bogo Sort

- [x] Bucket Sort

- [x] Cocktail Shaker Sort

- [x] Comb Sort

- [x] ~~Counting Sort~~

- [x] Pigeon Sort

- [x] Pancake Sort

- [x] Gnome Sort

- [x] External Sort

- [x] Double Sort

- [x] Cycle Sort 

- [ ] Slow Sort

Please comment on which one you would like to work on so that we can assign you. 
Please make separate PRs for every algorithm so that it gets easy for us to review as well. 
Join our slack channel <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> here. </a>. Keep Contributing. Thankyou :)

**Comment by ArunKumar-25** [comment]
@geekquad i would like to work on Insertion Sort, Selection Sort, Bubble Sort, Quick Sort assign this to me

**Comment by rudrakshi99** [comment]
Hey @geekquad, Please assign me Insertion sort, selection sort, and bubble sort.

**Comment by jigneshoo7** [comment]
Please assign me for  external sort, Cycle Sort

**Comment by geekquad** [comment]
Assigning  Insertion Sort, Selection Sort, Bubble Sort, and Quick Sort to @ArunKumar-25.
Assigning Merge Sort to @rudrakshi99.
Assigning External sort and Cycle Sort to @jigneshoo7.

**Comment by Iampradeepkundra** [comment]
can you assign me  Bucket Sort, Cocktail Shaker Sort, Comb Sort, Pigeon Sort, Pancake Sort!

**Comment by geekquad** [comment]
Assigning Bucket Sort and Cocktail Shaker Sort to @Iampradeepkundra.

**Comment by Anagha-2000** [comment]
hey, can you assign me: recursive bubble sort, recursive quicksort, recursive insertion sort @geekquad

**Comment by geekquad** [comment]
Assigning recursive bubble sort, recursive quicksort, and recursive insertion sort to @Anagha-2000

**Comment by ayangbori7** [comment]
I would really like to work on Merge Sort...i will add meaningful comments so that beginners will understand it easily.

**Comment by geekquad** [comment]
Hey @ayangbori7, merge sort is already taken. Assigning Heap Sort and Radix Sort to you. Thankyou :)

**Comment by iamKushagra** [comment]
Assign tree sort to me.

**Comment by kritikaparmar-programmer** [comment]
Please assign shell sort to me @geekquad

**Comment by geekquad** [comment]
Assigning Tree Sort to @iamKushagra.
Assigning Shell Sort to @kritikaparmar-programmer.

**Comment by iamKushagra** [comment]
Also, assign Wiggle Sort to me @geekquad

**Comment by geekquad** [comment]
Assigning Wiggle Sort to @iamKushagra.

**Comment by iamKushagra** [comment]
Assign me Bogo, Bead, and Comb Sort

**Comment by aishnayak** [comment]
hey plz assign me insertion and bubble sort

**Comment by geekquad** [comment]
Assigning Bogo, Bead, and Comb Sort to @iamKushagra

**Comment by aishnayak** [comment]
asign me pegion and pancake sort

**Comment by geekquad** [comment]
Assigning Pigeon and pancake sort to @aishnayak.

**Comment by Vrok2401** [comment]
Can you assign me on Gnome sort?

**Comment by ishneet890** [comment]
Assign me bubble sort @geekquad

**Comment by geekquad** [comment]
* Assigning Genome sort to @Vrok2401.

* Hey @ishneet890, Bubble sort is already taken by someone else. Please see if you can contribute to something else.

**Comment by kritikaparmar-programmer** [comment]
Hey @geekquad  Please assign Random Pivot Quick sort to me.

**Comment by geekquad** [comment]
Assigning  Random Pivot Quicksort to @kritikaparmar-programmer

**Comment by Aarti002** [comment]
@geekquad can i take double sort i will use python

**Comment by Aarti002** [comment]
if it is already assigned to someone then i will go with Tim sort and quick sort in python , is this fine? @geekquad

**Comment by geekquad** [comment]
Hey @Aarti002, I am sorry but these codes should be implemented in C++. If you want to contribute using the Python language please go [here](https://github.com/geekquad/AlgoBook/tree/master/python) and see if there is something missing and you would like to contribute. Please contact me on Slack for any queries. Thank you. 
Let me know if you need these issues in Cpp. Thankyou.

**Comment by Aarti002** [comment]
No problem i can also use cpp , now can i take all this issues? @geekquad

**Comment by geekquad** [comment]
Assigning Double and Tim sort to @Aarti002.
Quick Sort is already up with someone but we have more. Ask for others as well if you want to. Thankyou.

**Comment by bera5186** [comment]
@geekquad assign bitonic sort to me! I have made a pull request for all the previously assigned tasks! Thanks ;)

**Comment by bera5186** [comment]
> @geekquad assign bitonic sort to me! I have made a pull request for all the previously assigned tasks! Thanks ;)

???

**Comment by geekquad** [comment]
Assigning bitonic sort to @bera5186.

**Comment by Mansi145** [comment]
Hey, @geekquad, I'd like to work on the Gnome Sort Algorithm. Is the issue open for working?

**Comment by Mansi145** [comment]
Hey @geekquad, I'd like to work on the Stooge Sorting Algorithm. Is the issue open for contribution?

**Comment by geekquad** [comment]
Assigning Stooge Sorting Algorithm to @Mansi145.
