### ISSUE TITLE
I would like to contribute Runge kutta implementation, @geekquad could you you please assign me.

### ISSUE THREAD

**Issue by Kamesh-Mishra** [geekquad/AlgoBook#249]
I would like to contribute Runge kutta implementation, @geekquad could you you please assign me.

_Originally posted by @Kamesh-Mishra in https://github.com/geekquad/AlgoBook/issues/197#issuecomment-704871078_

**Comment by geekquad** [comment]
Hey @Kamesh-Mishra, is it the 4th order implementation?
