### ISSUE TITLE
Sorting Algorithms in Python

### ISSUE THREAD

**Issue by MAJOR-BEAST** [geekquad/AlgoBook#3]
- [x] ~~Insertion Sort~~

- [x] ~~Selection Sort~~

- [x] ~~Bubble Sort~~

- [x] ~~Heap Sort~~

- [x] ~~Quick Sort~~

- [x] ~~Radix Sort~~

- [x] ~~Merge Sort~~

- [x] ~~Topological Sort~~

**Comment by Siddhant-K-code** [comment]
three of them complete, please check my PR

**Comment by Aditi-1400** [comment]
Hey, I would like to work on this!

**Comment by MAJOR-BEAST** [comment]
> Hey, I would like to work on this!

Hey Aditi! 
Which issue would you like to work on? Remember, PRs will be counted from 1st Oct. Also, please join our slack channel too, and feel free to contact us there as well. Thank you  :)

**Comment by Aditi-1400** [comment]
I'd like to work on heap, quick and radix sort!

**Comment by geekquad** [comment]
Assigning Quick, Heap, and Radix sort to @Aditi-1400 
Remember, PRs will be counted from the 1st of October.
Please join our <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> Slack </a> channel as well. Thankyou :)

**Comment by bryonye** [comment]
Hi -- can I please be assigned the Bubble sort? Thanks!

**Comment by geekquad** [comment]
> Hi -- can I please be assigned the Bubble sort? Thanks!

Assigning Bubble sort to @bryonye 
Remember, PRs will be counted from the 1st of October.
Please join our slack channel as well. Happy Coding :)

**Comment by bhaveshlohana** [comment]
Hello, I'd like to work on Merge Sort.

**Comment by geekquad** [comment]
Assigning Merge Sort to @bhaveshlohana

**Comment by ABHI165** [comment]
hello, i'd like to work on Insertion Sort

**Comment by geekquad** [comment]
Assigning Insertion Sort to @ABHI165

**Comment by subhash1612** [comment]
Hey I would like to work on selection sort

**Comment by geekquad** [comment]
Assigning Selection Sort to @subhash1612 
Remember, PRs will be counted from the 1st of October.

**Comment by chaturvediabhay24** [comment]
Hi @geekquad can i work on tim sort and bucket sort which are not listed above.

**Comment by geekquad** [comment]
Hey @chaturvediabhay24 , please see refer them <a href="https://github.com/geekquad/AlgoBook/issues/8"> here</a>.

**Comment by gittygupta** [comment]
I would like to work on as many of the above as possible

**Comment by geekquad** [comment]
> I would like to work on as many of the above as possible

Hey @gittygupta, the issues above have already been assigned to people and we have received PRs for the same. But we are adding more issues. Meanwhile, just go through other issues as well and see if you can find something else to contribute to. Thank you :)

**Comment by riddhi-jain** [comment]
@geekquad I would like to work on Shell Sort.
