### ISSUE TITLE
Scheduling Algorithms in Python

### ISSUE THREAD

**Issue by Kamesh-Mishra** [geekquad/AlgoBook#303]
scheduling algorithms used in operating system like First come first served (FCFS), shortest job first (SJF), Priority Scheduling

**Comment by Kamesh-Mishra** [comment]
I would like to contribute 
>> First come first served (FCFS)
>> shortest job first (SJF)
>> Priority Scheduling,
could you please assign me @geekquad

**Comment by DasithEdirisinghe** [comment]
@geekquad I also prefer on CPU scheduling algorithms.If you could please assign me

**Comment by geekquad** [comment]
Yes, @DasithEdirisinghe. Go ahead.
