### ISSUE TITLE
Recommender system

### ISSUE THREAD

**Issue by ParthS28** [geekquad/AlgoBook#33]
Hello, can I add notebooks for a recommender system? 

I worked on one recently and it could fit here quite well.

Thanks.

**Comment by geekquad** [comment]
Sure @ParthS28 Go ahead. Can you please brief me out with the stacks used in the slack channel?

**Comment by akash22022** [comment]
Can I add notebook on Content based filtering

**Comment by ParthS28** [comment]
Hi @akash22022, there is already a notebook on content-based filtering. But if you have something to add to it, maybe you can edit the notebook without removing the original content. How does that sound @geekquad ? 
Also, we have collaborative filtering up for grabs right now. You can work on it if you want to. Thanks:)

**Comment by akash22022** [comment]
Ok then let me work on collaborative filtering

**Comment by geekquad** [comment]
Hey @akash22022, you can definitely work on the Collaborative Filtering. Thankyou :)
