### ISSUE TITLE
Algorithms in Go language

### ISSUE THREAD

**Issue by SoumyaMalgonde** [geekquad/AlgoBook#352]
Contribute various algorithms implemented in Go.

**Comment by SoumyaMalgonde** [comment]
Can I contribute to this?

**Comment by geekquad** [comment]
Sure @SoumyaMalgonde. Go ahead. Happy Coding :)

**Comment by bera5186** [comment]
@geekquad I would also like to contribute to this !! Can I ?

**Comment by AmanSingh0-0** [comment]
I would also like to contribute

**Comment by geekquad** [comment]
Sure @AmanSingh0-0. 
Check this out: [Sorting Algorithms in GO](https://github.com/geekquad/AlgoBook/issues/366)
