### ISSUE TITLE
N Queen's Problem of Backtracking

### ISSUE THREAD

**Issue by Vrindagupta6828** [geekquad/AlgoBook#372]
We can create a new folder of backtracking and add N queen's problem as of now.

**Comment by geekquad** [comment]
Hey @Vrindagupta6828, in which language would you like to implement?

**Comment by Vrindagupta6828** [comment]
@geekquad I can implement it in java, Python, c++

**Comment by Vrindagupta6828** [comment]
I would like to do it as part of kwoc

**Comment by geekquad** [comment]
Thankyou @Vrindagupta6828, Created an issue for the same. Please check:

- [ ] [Cpp](https://github.com/geekquad/AlgoBook/issues/374)

- [ ] [Python](https://github.com/geekquad/AlgoBook/issues/373)
