### ISSUE TITLE
Backtracking Problems in Python

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#373]
Implementation of the following in Python:

- [x] The Knight’s tour problem

- [x] Rat in a Maze

- [x] N Queen Problem

- [x] Subset Sum

- [x] m Coloring Problem

- [x] Hamiltonian Cycle

- [x] ~~Magnet Puzzle~~

To be merged in **"python/backtracking"** folder.

**Comment by Vrindagupta6828** [comment]
@geekquad  Please assign this to me .
I want to add N Queen's problem, Rat in a Maze.

**Comment by geekquad** [comment]
Sure @Vrindagupta6828. Go ahead.

**Comment by Vrindagupta6828** [comment]
I would like to add hamilton cycle and m coloring problem in this too

**Comment by geekquad** [comment]
Hey @Vrindagupta6828, you want to work on these two as well?

**Comment by Vrindagupta6828** [comment]
Yes

**Comment by geekquad** [comment]
Assigning you with hamilton cycle and m coloring problem @Vrindagupta6828.

**Comment by verma-shivani** [comment]
Please may I work on subset sum.

**Comment by geekquad** [comment]
Assigning Subset Sum to @verma-shivani.

**Comment by SounakMandal** [comment]
Hi, I want to work on the magnet puzzle. Can I be assigned the issue?

**Comment by geekquad** [comment]
Assigning magnet puzzle to @SounakMandal.

**Comment by Abhi-Kmr2046** [comment]
I want to work on the "The Knight’s tour problem".

**Comment by geekquad** [comment]
Assigning The Knight’s tour problem to @Abhi-Kmr2046.

**Comment by Pranjal-dew** [comment]
hi there, can I contribute to this issue?
