### ISSUE TITLE
Backtracking Problems in Cpp

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#374]
Implementation of the following in Cpp:

- [x] ~~The Knight’s tour problem~~

- [x] ~~Rat in a Maze~~

- [x] ~~N Queen Problem~~

- [x] ~~Subset Sum~~

- [x] ~~m Coloring Problem~~

- [x] ~~Hamiltonian Cycle~~

- [x] ~~Magnet Puzzle~~

To be merged in **"cpp/backtracking"** folder.

**Comment by Vrindagupta6828** [comment]
@geekquad Please assign this to me. 
I want to add Rat in a maze and N Queen's problem

**Comment by geekquad** [comment]
Assigning you with the same @Vrindagupta6828.

**Comment by itish-agarwal** [comment]
@geekquad please assign this to me
I want to work on  The Knight's tour problem, Subset sum, and m Coloring problem

**Comment by Vrindagupta6828** [comment]
Can you please assign me hamilton cycle as well

**Comment by geekquad** [comment]
Assigning The Knight's tour problem, Subset-sum, and m Coloring problem to @itish-agarwal.
Assigning Hamiltonian Cycle to @Vrindagupta6828.

**Comment by Aarushi11H** [comment]
Hey!
I'd like to take Magnet Puzzle problem

**Comment by geekquad** [comment]
Assigning Magnet Puzzle problem to @Aarushi11H.

**Comment by shash-2468** [comment]
I will work on Subset sum problem
@geekquad   please assign it to me

**Comment by geekquad** [comment]
Hey @shash-2468, the Subset sum problem is already assigned to someone else. Please see if you can contribute to some other issues.

**Comment by geekquad** [comment]
Hey @itish-agarwal, are you willing to complete the issues assigned to you?

**Comment by shash-2468** [comment]
Okay @geekquad , If @itish-agarwal isn't willing to do then assign me please!!

**Comment by itish-agarwal** [comment]
Yes please assign the issue to @shash-2468 as i am not able to complete it

**Comment by geekquad** [comment]
Assigning Knight's tour problem, Subset-sum, and m Coloring problem to @shash-2468.

**Comment by shash-2468** [comment]
everything is solved in this issue.
close this
