### ISSUE TITLE
Algorithms in Java

### ISSUE THREAD

**Issue by maheshvpawar** [geekquad/AlgoBook#397]
@geekquad I would be happy to contribute for algorithms in Java. Let me know if you think about it. Thank You!

**Comment by satyam20-sys** [comment]
I also can contribute in java, please let me know if I can be helpful in anyway Thank you !

**Comment by geekquad** [comment]
Hey @maheshvpawar and @satyam20-sys, we are not opening any issues for Java yet but we are planning it. I will let you guys know once it is there, Thankyou for bringing it up. :)
