### ISSUE TITLE
Add 2 new folders in Python folder

### ISSUE THREAD

**Issue by hr1shu** [geekquad/AlgoBook#399]
Just want to add 'RECURSION' and 'TRAVERSAL' codes in the python language under the **python** folder.
**Allow me for further PRs**

**Comment by geekquad** [comment]
Hey @hr1shum, which algorithms will you implement in each domain?

**Comment by hr1shu** [comment]
For traversal, I'll be implementing DFS & BFS.
For recursion, Factorial, Fibonacci and one more.
All will be in python language.

**Comment by hr1shu** [comment]
Should I proceed, Sir?

**Comment by geekquad** [comment]
Hey @hr1shu, please check the code section:
- DFS & BFS are already implemented [here](https://github.com/geekquad/AlgoBook/tree/master/python/searching).
- Fibbonacci [here](https://github.com/geekquad/AlgoBook/tree/master/python/dynamic_programming). 
- You can add Fibonacci file but make sure to add it in the **"python/maths"** folder.

**Comment by hr1shu** [comment]
I'll be implementing Fibonacci and Factorial in recursion.
The Fibonacci already implemented is in the dynamic programming section.

**Comment by hr1shu** [comment]
Ok 👍

**Comment by hr1shu** [comment]
Thanks buddy
