### ISSUE TITLE
Want to add an excel file

### ISSUE THREAD

**Issue by hr1shu** [geekquad/AlgoBook#400]
The file contains 450+ questions of DSA with direct links to solutions and tutorials. The questions are sorted according to different topics of DSA. It is named as DSA cracker series. Once you solve all the questions, you will cover all the patterns and types of questions and can ace your problem-solving skills.
**I'll love to contribute to all the students like me out there.**

**Comment by geekquad** [comment]
We are not open to any sort of DSA questions or practice sheets. The aim of this repo is to have implementations of all sorts of algorithms. So we are currently focusing on that.

**Comment by hr1shu** [comment]
Gotcha, thanks
