### ISSUE TITLE
A cheat sheet folder

### ISSUE THREAD

**Issue by hr1shu** [geekquad/AlgoBook#406]
A cheat sheet is a quick guide to everything and I have an abundance of cheat sheets of different topics.
For example, Python cheat sheet, Big-O cheat sheet, react cheat sheet, and many more. 
You can tell me which topics I would be including. 
I'm glad to contribute to your resources.

**Comment by Ak-panchal** [comment]
Can I work on this issue?

**Comment by geekquad** [comment]
Hey @Ak-panchal, please send me a sample? Please join the community on Slack and reach out to me. Thanks.
