### ISSUE TITLE
add a text summarizer

### ISSUE THREAD

**Issue by manish2202** [geekquad/AlgoBook#407]
1. based on extractive text summarization
2. use of cosine similarity where sentences are ranked based on the similarity (zero angle if similar sentences).
3. uses NLTK for tokenizing words/sentences and for removing stopwords (of English language).
4. a frequency table is also created to check the frequency of words. 

Here is the text document containing the entire code

[Text Summarizer using NLTK.txt](https://github.com/geekquad/AlgoBook/files/5667578/Text.Summarizer.using.NLTK.txt)

**Comment by geekquad** [comment]
Hey @manish2202, try to make a pipeline of the code. I will review it and ask for necessary changes if needed. Add a requirements.txt file as well.

**Comment by manish2202** [comment]
Okay. Thanks

**Comment by manish2202** [comment]
> Hey @manish2202, try to make a pipeline of the code. I will review it and ask for necessary changes if needed. Add a requirements.txt file as well.
> You are allowed to create an NLP folder as well. Make it "nlp".
> The file structure should look like this:
> 
> > AlgoBook
> > nlp
> > > test summarizer
> > > > file.py

Hello, I have done the necessary changes. Would you mind checking it? I had some work out of station so I couldn't work earlier.
