### ISSUE TITLE
Adding Iris Plant classification from a given dataset

### ISSUE THREAD

**Issue by manish2202** [geekquad/AlgoBook#408]
1. use of matplotlib and numpy.
2. use of iris plant dataset.
3. use of logistic regression.
4. visual representation.
5. dividing the dataset into training and testing purposes.
[irisml.txt](https://github.com/geekquad/AlgoBook/files/5667663/irisml.txt)

**Comment by geekquad** [comment]
Hey, @manish2202. As you can see we are implementing various algorithms here. And logistic regression is already implemented. Please refer to the codebase. If we have missed any algorithm and you would like to implement the same, then you are most welcome. Thankyou :)
