### ISSUE TITLE
Topological sort needs to be added

### ISSUE THREAD

**Issue by 18Pranjul** [geekquad/AlgoBook#423]
Can you assign me this issue?

**Comment by geekquad** [comment]
Hey @18Pranjul, where would you like to add this?

**Comment by 18Pranjul** [comment]
Yes, sure.

**Comment by geekquad** [comment]
Hey @18Pranjul, I am asking where do you want to add this? I have not assigned you anything here. Please brief out!

**Comment by 18Pranjul** [comment]
> Hey @18Pranjul, I am asking where do you want to add this? I have not assigned you anything here. Please brief out!

I would like to add this in cpp/Graphs algorithms.

**Comment by geekquad** [comment]
Go ahead. Please add this in **"cpp/sorting"**.
