### ISSUE TITLE
String algorithms needs to be added.

### ISSUE THREAD

**Issue by 18Pranjul** [geekquad/AlgoBook#445]
These algos needs to be added in a new folder /cpp/Strings/

- [ ] KMP Algorithm
- [ ] Z-Algorithm

**Comment by 18Pranjul** [comment]
Can you please assign me this issue?

**Comment by LakhanMardi** [comment]
@geekquad can I work on kmp algorithm?

**Comment by geekquad** [comment]
Hey @18Pranjul and @LakhanMardi thankyou. 
Created an issue for the same. Please check it out [here](https://github.com/geekquad/AlgoBook/issues/446)
