### ISSUE TITLE
String Algorithms Cpp

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#446]
String algorithms: 

- [x] String Hashing

- [x] Rabin-Karp for String Matching

- [x] Prefix function - Knuth-Morris-Pratt

- [x] Z-function

- [x] Suffix Array

- [x] Aho-Corasick algorithm

- [x] KMP Algorithm

**Comment by geekquad** [comment]
Assigning Z and KMP algorithm to @18Pranjul.

**Comment by RhuthuHegde** [comment]
can I work on string hashing?

**Comment by geekquad** [comment]
Assigning String Hashing to @RhuthuHegde.

**Comment by LakhanMardi** [comment]
@geekquad  can i work on rabin-karp algo???

**Comment by RhuthuHegde** [comment]
Can you please guide me and let me know what exactly to be included in the string hashing algorithm?

**Comment by verma-shivani** [comment]
May I work on Suffix Array?

**Comment by geekquad** [comment]
Assigning Rabin-Karp for String Matching to @LakhanMardi.
Assigning Suffix Array to @verma-shivani.
Hey @RhuthuHegde, String hashing is the way to convert a string into an integer known as a hash of that string. The goal of it is to convert a string into an integer, the so-called hash of the string. The following condition has to hold:
* If two strings s and t are equal (s=t), then also their hashes have to be equal.
> Feel free to reach out to me on our [Slack channel](https://join.slack.com/t/geekquad/shared_invite/zt-jtdqxt2r-i9R7vvNPzveImCBBM~eahw) for any further queries.

**Comment by divyanshjoshi** [comment]
anything there to work on??

**Comment by geekquad** [comment]
Yes @divyanshjoshi, we still have these two available:
- [ ] Prefix function - Knuth-Morris-Pratt
- [ ] Aho-Corasick algorithm

**Comment by divyanshjoshi** [comment]
Okay, I'll go for the aho-corasik algorithm

**Comment by geekquad** [comment]
Assigning Aho-Corasick algorithm to @divyanshjoshi.

**Comment by JordanVanLeeuwen** [comment]
Hello, mind if I take a crack at the prefix function?

**Comment by geekquad** [comment]
Sure @JordanVanLeeuwen, go ahead mate!

**Comment by divyanshjoshi** [comment]
hey is there a deadline for the pull requests to be made?

**Comment by atom19-i** [comment]
hey,is there anything i can work on,here?
