### ISSUE TITLE
Implementation of beginner Unsupervised ML Algorithms

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#6]
Unsupervised learning models are used when we only have the input variables (X) and no corresponding output variables.
Implementation of beginner Unsupervised Learning Algos:

- [x] ~~Apriori~~

- [x] ~~K-means~~

- [x] ~~PCA~~

- [x] ~~ICA~~

**Comment by kritikaparmar-programmer** [comment]
Hey @geekquad  Do we have to write custom implementation of the given algos?
If yes then please assign me K-means . So that I can start working on it..

**Comment by geekquad** [comment]
Assigning K-Means to @kritikaparmar-programmer 
Happy Coding :)

**Comment by chaturvediabhay24** [comment]
i would like to work on pca. please assign me the same.

**Comment by geekquad** [comment]
Assigning @chaturvediabhay24 with PCA.

**Comment by rajatsahay** [comment]
Hey @geekquad 
If ICA is independent component analysis, I would like to work on that. Request you to assign the issue to me.
Thanks

**Comment by geekquad** [comment]
> Hey @geekquad
> If ICA is independent component analysis, I would like to work on that. Request you to assign the issue to me.
> Thanks

Yes @rajatsahay, ICA is Independent component analysis. Assigning you to it.

**Comment by Zafershah24** [comment]
Hey @geekquad can I work on PCA?

**Comment by chaturvediabhay24** [comment]
hey @Zafershah24 I have been assigned PCA and I have already submitted pull request for the same.

**Comment by bera5186** [comment]
@geekquad @MAJOR-BEAST can I do apriori?

**Comment by geekquad** [comment]
Assigning Apriori to @bera5186.

**Comment by geekquad** [comment]
Hey @bera5186, it's been quite a while. Are you willing to complete the tasks assigned to you or should we unassign you? Please do let me know. Thankyou.

**Comment by bera5186** [comment]
@geekquad Just 2 More Days !! I won't Disappoint you !!

**Comment by geekquad** [comment]
No issues @bera5186. Take your time :)

**Comment by amoghatsunil** [comment]
@geekquad  can i please do apriori?

**Comment by geekquad** [comment]
Hey @amoghatsunil, apriori is already implemented. Adding more issues soon. Join the Slack channel for updates. Thankyou :)
