### ISSUE TITLE
Searching Algorithms in Python 

### ISSUE THREAD

**Issue by geekquad** [geekquad/AlgoBook#7]
- [x] ~~Linear Search~~

- [x] ~~Binary Search~~

- [x] ~~Bilinear Search (Improvised version of Linear Search)~~

- [x] ~~Breadth First Search~~

- [x] ~~Depth First Search~~

- [x] ~~Exponential Search~~

- [x] ~~Interpolation Search~~

- [x] ~~Z Algorithm~~

- [x] Fibonacci Search

- [x] ~~Jump Search~~

- [x] ~~Ternary Search~~

- [x] ~~Sublist Search~~

**Comment by sravanireddy1102** [comment]
Hey!Can I work on this?

**Comment by geekquad** [comment]
> Hey! Can I work on this?

Hello! Which issue would you like to work on?
Also please join our slack channel and feel free to contact us there too. Thank you :)

**Comment by sravanireddy1102** [comment]
Can I add some algorithms to the repository? Linear search ,Binary search
and also some sorting algorithms in python

**Comment by kritikaparmar-programmer** [comment]
Hey @geekquad can I work on Linear Search and Binary Search?

**Comment by ChiragSharma1** [comment]
can i work Depth First and Breadth first Search?

**Comment by MAJOR-BEAST** [comment]
> can i work Depth First and Breadth first Search?

From tomorrow on we'll be assigning everyone with whatever you guys want to contribute. But please join the slack channel as well. And try to message  in the group rather than PM on the channel.
@ChiragSharma1 @kritikaparmar-programmer @sravanireddy1102

**Comment by MAJOR-BEAST** [comment]
We'll assign you all shortly. Remember PRs will he counted from 1st October (that is by midnight). 
Please do join the slack channel as well.
@ChiragSharma1 @sravanireddy1102 @kritikaparmar-programmer

**Comment by geekquad** [comment]
Hey @sravanireddy1102 please be specific which issues would you like to take so that it avoids any sort of confusion to others while they check upon the issues. Assigning **Linear** and **Binary** search to you. 
Remember, PRs will be counted from 1st October. Make separate PRs for each one of them. 
For any queries, please join our <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> Slack </a> channel as well.

**Comment by Siddhant-K-code** [comment]
I would like to work on Ternary Search 

pls assign me with that @geekquad

**Comment by geekquad** [comment]
Assigning Ternary Search to @Siddhant-K-code

**Comment by MAJOR-BEAST** [comment]
Assigning **Depth First Search** and **Breadth First Search** to @ChiragSharma1 . Happy Coding :)

**Comment by vlx01** [comment]
Hey @geekquad, I'd like to take on the Sublist search.

**Comment by geekquad** [comment]
Assigning Sublist Search to @vlx01

**Comment by subhash1612** [comment]
Hey @geekquad  I would like to work on jump search

**Comment by geekquad** [comment]
Assigning Jump Search to @subhash1612 
Remember, PRs will be counted from 1st October. 
For any queries, please join our <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> Slack </a> channel as well.

**Comment by subhash1612** [comment]
Hey @geekquad I would also like to work on exponential search

**Comment by geekquad** [comment]
Assigning Exponential Search to @subhash1612

**Comment by chaturvediabhay24** [comment]
Hi @geekquad i would like to work on fibonacci search. please assign me the same.

**Comment by geekquad** [comment]
Assigning Fibonacci Search to @chaturvediabhay24 
Remember, PRs will be counted from 1st October. 
Please join our <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> Slack </a> channel as well.

**Comment by rohitjoshi6** [comment]
Hey @geekquad i would love work on linear search and jump search?

**Comment by geekquad** [comment]
> Hey @geekquad i would love work on linear search and jump search?

Hello @rohitjoshi6, Linear Search and Jump search has already been taken up by the contributors.
However we still have Interpolation Search here as well as several Sorting Algorithms <a href="https://github.com/geekquad/AlgoBook/issues/8#issuecomment-701458887"> here</a>.
Do let me know if you want to work on any of these. 
Please join our <a href="https://join.slack.com/t/geekquad/shared_invite/zt-i117xz40-6eN05mvvci4eIdsrU1ehcA"> Slack </a> channel.

**Comment by rohitjoshi6** [comment]
Hey @geekquad can i work on interpolation search??

**Comment by geekquad** [comment]
Assigning Interpolation Search to @rohitjoshi6

**Comment by rajatsahay** [comment]
Hey
I could implement the Z algorithm in Python. Would love to work on this

**Comment by geekquad** [comment]
> Hey
> I could implement the Z algorithm in Python. Would love to work on this

Hey @rajatsahay, Z algorithm is already implemented but we have plenty in <a href="https://github.com/geekquad/AlgoBook/issues/20"> Matrix </a>, <a href="https://github.com/geekquad/AlgoBook/issues/16"> Graph </a> and <a href="https://github.com/geekquad/AlgoBook/issues/8"> Sorting </a>. 
See if you can contribute with something else. Thankyou :)

**Comment by rajatsahay** [comment]
That's cool. Thanks

**Comment by bhaveshlohana** [comment]
Can I do Fibonacci search?

**Comment by shaswatsingh19** [comment]
can I do z algorithm

**Comment by Siddhant-K-code** [comment]
@shaswatsingh19 it is already done, please go through [this](https://github.com/geekquad/AlgoBook/issues/7) issue, many of the tasks are Assigned/Completed

**Comment by geekquad** [comment]
> Can I do Fibonacci search?

Hey @bhaveshlohana, Fibonacci Search has already been assigned to someone else, but we have plenty in <a href="https://github.com/geekquad/AlgoBook/issues/20"> Matrix </a>, <a href="https://github.com/geekquad/AlgoBook/issues/61"> String </a>,<a href="https://github.com/geekquad/AlgoBook/issues/16"> Graph </a> and <a href="https://github.com/geekquad/AlgoBook/issues/8"> Sorting </a>. 
See if you can contribute with something else. Thankyou :)

**Comment by onowdev** [comment]
I have done a pull request for the Interpolation search algorithm, please review it, @geekquad

**Comment by riddhi-jain** [comment]
@geekquad please assign me Interpolation Search.

**Comment by MAJOR-BEAST** [comment]
> I have done a pull request for the Interpolation search algorithm, please review it, @geekquad

Give us some time @onowdev , since there are many PRs, we are still working on it. Soon it will be reviewed.

**Comment by Raghavarora27** [comment]
can u assign me something???

**Comment by Aarti002** [comment]
@geekquad can i do Fibonacci Search in python?

**Comment by amoghatsunil** [comment]
@geekquad can i do Fibonacci search or A* in python?

**Comment by geekquad** [comment]
Sure @amoghatsunil. Go ahead.
